services:
  - type: web
    name: football-predictions
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: API_FOOTBALL_KEY
        sync: false 